spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://100.64.208.218:3306/LabSystem?useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
    http:
      encoding:
        charset: UTF-8
        enabled: true
        force: true